import { type Course } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useForm } from "@mantine/form";
import AdminDashboardLayout from "~/components/layouts/admin-dashboard-layout";
import {
  Card as MantineCard,
  Image,
  Text,
  Flex,
  Grid,
  Button,
  Group,
  Modal,
  TextInput,
  Stack,
  Textarea,
} from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { api } from "~/utils/api";

export function CourseCard({ course }: { course: Course }) {
  return (
    <MantineCard shadow="sm" padding="lg" radius="md" withBorder>
      <MantineCard.Section>
        <Image
          src="https://images.unsplash.com/photo-1527004013197-933c4bb611b3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=720&q=80"
          height={160}
          alt="Norway"
        />
      </MantineCard.Section>

      <Group position="apart" mt="md" mb="xs">
        <Text weight={500}>{course.title}</Text>
        {/* <Badge color="pink" variant="light">
          On Sale
        </Badge> */}
      </Group>

      <Text size="sm" color="dimmed">
        {course.description}
      </Text>

      <Button variant="light" color="blue" fullWidth mt="md" radius="md">
        Manage
      </Button>
    </MantineCard>
  );
}

const Courses: NextPage = () => {
  const courses = api.course.getCourses.useQuery();

  const createCourseMutation = api.course.createCourse.useMutation();

  const [
    isCreateCourseModalOpen,
    { open: openCreateCourseModal, close: closeCreateCourseModal },
  ] = useDisclosure(false);

  const createCourseForm = useForm({
    initialValues: {
      title: "",
      description: "",
    },
  });

  return (
    <>
      <Head>
        <title>Manage Courses</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal
        opened={isCreateCourseModalOpen}
        onClose={closeCreateCourseModal}
        title="Create Course"
      >
        <form
          onSubmit={createCourseForm.onSubmit(async (values) => {
            await createCourseMutation.mutateAsync(values);
            closeCreateCourseModal();
            createCourseForm.reset();
            await courses.refetch();
          })}
        >
          <Stack>
            <TextInput
              withAsterisk
              label="Title"
              required
              placeholder="name your course here"
              {...createCourseForm.getInputProps("title")}
            />

            <Textarea
              withAsterisk
              minRows={6}
              required
              label="Description"
              placeholder="describe your course a bit"
              {...createCourseForm.getInputProps("description")}
            />
          </Stack>

          <Group position="right" mt="md">
            <Button type="submit">Create Course</Button>
          </Group>
        </form>
      </Modal>
      <main>
        <AdminDashboardLayout>
          <Flex justify="space-between" align="center" direction="row">
            <h1>Manage Courses</h1>

            <Button onClick={openCreateCourseModal}>Create Course</Button>
          </Flex>

          <Grid>
            {courses.data?.map((course) => (
              <Grid.Col key={course.id} span={4}>
                <CourseCard course={course} />
              </Grid.Col>
            ))}
          </Grid>
        </AdminDashboardLayout>
      </main>
    </>
  );
};

export default Courses;
