import { type NextPage } from "next";
import Head from "next/head";
import AdminDashboardLayout from "~/components/layouts/admin-dashboard-layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AdminDashboardLayout>Dashboard</AdminDashboardLayout>
      </main>
    </>
  );
};

export default Home;
